/**
 * Decide what Dockerfile to use for an arbitrary cloned repo.
 *
 * Strategy:
 *   1. If the repo already has a Dockerfile, use it as-is.
 *   2. Otherwise, sniff the repo for known stacks (Node, Python, Go, Java)
 *      and synthesise a minimal Dockerfile appropriate for the dev env.
 *
 * The generated Dockerfile is intentionally simple — production users should
 * supply their own. This is a sane default so the demo flow works even when
 * the agent operates on a vanilla repo.
 */

import { readFile, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';

export interface DockerfileResult {
  /** Path to the Dockerfile relative to the workspace root. */
  dockerfile: string;
  /** Container port the app listens on. */
  port: number;
  /** True when the file was synthesised by us. */
  generated: boolean;
  /** Human-readable explanation of the decision. */
  notes: string;
}

async function exists(p: string): Promise<boolean> {
  try {
    const s = await stat(p);
    return s.isFile() || s.isDirectory();
  } catch {
    return false;
  }
}

async function readJsonSafe<T>(p: string): Promise<T | undefined> {
  try {
    const raw = await readFile(p, 'utf8');
    return JSON.parse(raw) as T;
  } catch {
    return undefined;
  }
}

interface PackageJson {
  scripts?: Record<string, string>;
  dependencies?: Record<string, string>;
  devDependencies?: Record<string, string>;
  main?: string;
}

async function generateNodeDockerfile(cwd: string): Promise<DockerfileResult> {
  const pkg = (await readJsonSafe<PackageJson>(path.join(cwd, 'package.json'))) ?? {};
  const scripts = pkg.scripts ?? {};
  const deps = { ...(pkg.dependencies ?? {}), ...(pkg.devDependencies ?? {}) };

  const isNext = !!deps['next'];
  const startCmd = scripts['start']
    ? 'npm start'
    : scripts['dev']
      ? 'npm run dev'
      : pkg.main
        ? `node ${pkg.main}`
        : 'node index.js';
  const buildCmd = scripts['build'] ? 'RUN npm run build' : '';
  const port = isNext ? 3000 : 8080;

  const content = `# Auto-generated by Liliput — replace with your own Dockerfile when ready.
FROM node:22-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --no-audit --no-fund
COPY . .
${buildCmd}
ENV PORT=${port}
EXPOSE ${port}
CMD ["sh", "-c", "${startCmd}"]
`;

  await writeFile(path.join(cwd, 'Dockerfile.liliput'), content, 'utf8');
  return {
    dockerfile: 'Dockerfile.liliput',
    port,
    generated: true,
    notes: `Generated Node.js Dockerfile (start: ${startCmd}, port: ${port}).`,
  };
}

async function generatePythonDockerfile(cwd: string): Promise<DockerfileResult> {
  const hasReqs = await exists(path.join(cwd, 'requirements.txt'));
  const port = 8000;
  const content = `# Auto-generated by Liliput — replace with your own Dockerfile when ready.
FROM python:3.12-slim
WORKDIR /app
COPY . .
${hasReqs ? 'RUN pip install --no-cache-dir -r requirements.txt' : 'RUN pip install --no-cache-dir flask'}
ENV PORT=${port}
EXPOSE ${port}
CMD ["python", "-m", "http.server", "${port}"]
`;
  await writeFile(path.join(cwd, 'Dockerfile.liliput'), content, 'utf8');
  return {
    dockerfile: 'Dockerfile.liliput',
    port,
    generated: true,
    notes: `Generated Python Dockerfile (port: ${port}).`,
  };
}

async function generateStaticDockerfile(cwd: string): Promise<DockerfileResult> {
  const port = 80;
  const content = `# Auto-generated by Liliput — static-site fallback.
FROM nginx:1-alpine
COPY . /usr/share/nginx/html
EXPOSE ${port}
`;
  await writeFile(path.join(cwd, 'Dockerfile.liliput'), content, 'utf8');
  return {
    dockerfile: 'Dockerfile.liliput',
    port,
    generated: true,
    notes: 'Generated static-site Dockerfile (no detected stack).',
  };
}

export async function resolveDockerfile(cwd: string): Promise<DockerfileResult> {
  // 1. Existing Dockerfile wins.
  for (const candidate of ['Dockerfile', 'src/api/Dockerfile', 'Dockerfile.dev']) {
    const p = path.join(cwd, candidate);
    if (await exists(p)) {
      // Best-effort port detection
      let port = 8080;
      try {
        const content = await readFile(p, 'utf8');
        const match = content.match(/EXPOSE\s+(\d+)/i);
        if (match?.[1]) port = parseInt(match[1], 10);
      } catch {
        /* ignore */
      }
      return {
        dockerfile: candidate,
        port,
        generated: false,
        notes: `Using existing Dockerfile at ${candidate} (port: ${port}).`,
      };
    }
  }

  // 2. Sniff stack
  if (await exists(path.join(cwd, 'package.json'))) {
    return generateNodeDockerfile(cwd);
  }
  if (
    (await exists(path.join(cwd, 'requirements.txt'))) ||
    (await exists(path.join(cwd, 'pyproject.toml')))
  ) {
    return generatePythonDockerfile(cwd);
  }

  // 3. Static fallback
  return generateStaticDockerfile(cwd);
}
