/**
 * Template-based spec generator.
 * Produces a structured markdown spec from a task description.
 * Will be replaced with LLM-powered generation later.
 */
export function generateSpec(title: string, description: string): string {
  return `# Specification: ${title}

## Overview
${description}

## Requirements
1. The system shall implement the functionality described above.
2. All changes must include appropriate unit and integration tests.
3. Code must follow existing project conventions and pass linting.
4. Error handling must cover all edge cases.

## Acceptance Criteria
- [ ] Feature works as described in the overview
- [ ] Unit tests pass with adequate coverage
- [ ] Integration tests verify end-to-end flow
- [ ] No regressions in existing functionality
- [ ] Code review approved

## Technical Approach
1. **Analysis** — Review existing codebase for impact areas
2. **Design** — Define interfaces and data flow
3. **Implementation** — Write code following TDD approach
4. **Testing** — Verify with unit, integration, and e2e tests
5. **Deployment** — Deploy via CI/CD pipeline

---
*Generated by Liliput Spec Generator*
`;
}
