import { approveAll } from '@github/copilot-sdk';
import { getCopilotClient } from './copilot-client.js';
import {
  classifyError,
  recordAuthFailure,
  recordAuthSuccess,
  type AuthStatus,
  getAuthStatus,
} from './auth-status.js';
import { logger } from '../logger.js';

const DEFAULT_MODEL = process.env['COPILOT_MODEL'] ?? 'gpt-5';
const DEFAULT_TIMEOUT_MS = parseInt(process.env['COPILOT_TIMEOUT_MS'] ?? '120000', 10);
const PROBE_TIMEOUT_MS = parseInt(process.env['COPILOT_PROBE_TIMEOUT_MS'] ?? '30000', 10);

function buildPrompt(title: string, description: string): string {
  return [
    'You are a senior software engineer drafting a concise, implementation-ready specification.',
    'Output ONLY the specification as GitHub-Flavored Markdown — no preamble, no explanation, no code fences around the whole document.',
    '',
    'The spec MUST contain these sections in this order:',
    '1. `# Specification: <title>`',
    '2. `## Overview` — 2–4 sentences summarising the goal',
    '3. `## Requirements` — numbered functional + non-functional requirements',
    '4. `## Acceptance Criteria` — checkbox list (`- [ ]`) covering observable outcomes',
    '5. `## Technical Approach` — ordered steps an engineer would follow',
    '6. `## Out of Scope` — bullets listing what is explicitly NOT included',
    '',
    `Task title: ${title}`,
    '',
    'Task description and conversation context:',
    description,
  ].join('\n');
}

function stripCodeFence(content: string): string {
  const trimmed = content.trim();
  const fenceMatch = trimmed.match(/^```(?:markdown|md)?\n([\s\S]*?)\n```$/i);
  return fenceMatch?.[1]?.trim() ?? trimmed;
}

function fallbackSpec(title: string, description: string, reason: string): string {
  logger.warn({ reason }, 'Falling back to template spec');
  return `# Specification: ${title}

## Overview
${description}

## Requirements
1. The system shall implement the functionality described above.
2. All changes must include appropriate unit and integration tests.
3. Code must follow existing project conventions and pass linting.
4. Error handling must cover all edge cases.

## Acceptance Criteria
- [ ] Feature works as described in the overview
- [ ] Unit tests pass with adequate coverage
- [ ] Integration tests verify end-to-end flow
- [ ] No regressions in existing functionality
- [ ] Code review approved

## Technical Approach
1. **Analysis** — Review existing codebase for impact areas
2. **Design** — Define interfaces and data flow
3. **Implementation** — Write code following TDD approach
4. **Testing** — Verify with unit, integration, and e2e tests
5. **Deployment** — Deploy via CI/CD pipeline

---
*Generated by Liliput template fallback (${reason})*
`;
}

export type SpecGenerator = (title: string, description: string) => Promise<string>;

/**
 * Generate a markdown spec for a task using the GitHub Copilot SDK.
 * Falls back to a static template if the LLM call fails or times out.
 * Records auth health on every call.
 */
export async function generateSpec(title: string, description: string): Promise<string> {
  const prompt = buildPrompt(title, description);

  try {
    const client = await getCopilotClient();
    const session = await client.createSession({
      model: DEFAULT_MODEL,
      onPermissionRequest: approveAll,
    });

    try {
      const result = await session.sendAndWait({ prompt }, DEFAULT_TIMEOUT_MS);
      const content = result?.data?.content?.trim();
      if (!content) {
        recordAuthFailure('unknown', 'Empty response from the LLM');
        return fallbackSpec(title, description, 'empty LLM response');
      }
      recordAuthSuccess();
      logger.info({ model: DEFAULT_MODEL, chars: content.length }, 'Spec generated via Copilot SDK');
      return stripCodeFence(content);
    } finally {
      await session.disconnect().catch((err: unknown) => {
        const message = err instanceof Error ? err.message : String(err);
        logger.warn({ err: message }, 'Error disconnecting Copilot session');
      });
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    const { kind, message: humanMsg } = classifyError(err);
    recordAuthFailure(kind, humanMsg);
    logger.error({ err: message, kind }, 'Copilot SDK spec generation failed');
    return fallbackSpec(title, description, message);
  }
}

/**
 * Lightweight active probe — sends a tiny prompt to verify auth + connectivity.
 * Returns the resulting auth status. Used by `POST /api/auth/check`.
 */
export async function probeAuth(): Promise<AuthStatus> {
  try {
    const client = await getCopilotClient();
    const session = await client.createSession({
      model: DEFAULT_MODEL,
      onPermissionRequest: approveAll,
    });
    try {
      const result = await session.sendAndWait(
        { prompt: 'Reply with the single word: ok' },
        PROBE_TIMEOUT_MS,
      );
      if (!result?.data?.content) {
        recordAuthFailure('unknown', 'Probe returned an empty response');
      } else {
        recordAuthSuccess();
      }
    } finally {
      await session.disconnect().catch(() => undefined);
    }
  } catch (err: unknown) {
    const { kind, message } = classifyError(err);
    recordAuthFailure(kind, message);
  }
  return getAuthStatus();
}
